name: Flutter CI
on: workflow_dispatch
jobs:
 build_apk:
   name: Build Flutter (Android)
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-java@v1
       with:
       java-version: "12.x"
     - uses: subosito/flutter-action@v1
       with:
         channel: "stable"
       env:
         KEY_JKS: ${{ secrets.KEYSTORE }}
         SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
         SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
         SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
     - name: Decode Keystore
       run: |
         cat "${{secrets.KEYSTORE}}" | base64 --decode > android/key.jks
     - name: Create key.properties
       run: |
         touch android/key.properties
       echo "storePassword=${{ secrets.STORE_PASSWORD }}
       keyPassword=${{ secrets.KEY_PASSWORD }}
       keyAlias=${{ secrets.ALIAS }}
       storeFile=../key.jks"  > ./android/key.properties
     - name: Get dependencies
       run: flutter pub get
     - name: Build APK
       run: flutter build apk
     - uses: actions/upload-artifact@v1
       with:
         name: release-apk
         path: build/app/outputs/apk/release/app-release.apk
